### ISSUE TITLE
Technologies for creative industries, social media and convergence

### ISSUE THREAD

**Issue by pgstacey** [creativecommons/Open-business-models#8]
Look into the "Technologies for creative industries, social media and convergence" research project the guys from Greece want us to partner on:

http://ec.europa.eu/research/participants/portal/desktop/en/opportunities/h2020/topics/9085-ict-19-2015.html

High level summary of due date for proposals, potential dollar value of awards, themes or areas of focus for the grants, date by which work must be complete, that kind of thing.

**Comment by sarahpearson** [comment]
Read latest proposal before Thursday call.
