### ISSUE TITLE
Activity #5 Partnership Framework

### ISSUE THREAD

**Issue by pgstacey** [creativecommons/Open-business-models#9]
Need to draft some kind of basic MOU like document that outlines expectations we have of people/orgs we partner with on activity #5 and also what they get back in return from us.

**Comment by sarahpearson** [comment]
@pgstacey I drafted this last week: https://github.com/creativecommons/Open-business-models/wiki/Activity-%235:-Collaboratively-designing-an-open-business-model

Did you want something more agreement-like?

**Comment by pgstacey** [comment]
Ahh, excellent this looks good. Thanks. I think this will suffice for now. I'm expecting at some point though that a partner may want us to provide something agreement-like but lets wait till that happens.
